---
- name: setup mysql
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
  - name: Removes all anonymous user accounts
    mysql_user: name='' host_all=yes state=absent
    
  - name: Create database user with name 'bob' and password '12345' with all database privileges
    mysql_user:
      name: bob
      password: 12345
      priv: '*.*:ALL'
      state: present
      
  - name: Create a new database with name 'data'
    mysql_db:
      name: data
      state: present