---
- name: remove lamp stack
  hosts: all
  remote_user: testserver2
  become: yes

  tasks:
  - name: remove apache
    apt: name="{{ packages }}" state=absent
    vars:
      packages:
      - apache2
      - apache2-doc
      - apache2-utils
      - libexpat1
      - ssl-cert
      
  - name: remove mysql
    apt: name="{{ packages }}" state=absent
    vars:
      packages:
      - mysql-server
      - mysql-client
      
  - name: remove php
    apt: name="{{ packages }}" state=absent
    vars:
      packages:
      - libapache2-mod-php7.2 
      - php7.2 
      - php7.2-common 
      - php7.2-curl 
      - php7.2-dev 
      - php7.2-gd 
      - php-pear 
      - php-imagick  
      - php7.2-mysql 
      - php7.2-ps 
      - php7.2-xsl 
      - php-json 
      - php-cgi
      
  - name: remove phpmyadmin
    apt: name=phpmyadmin state=absent